### ISSUE TITLE
Can i use your source code?

### ISSUE THREAD

**Issue by ghost** [doublemetal/doublemetal.github.io#2]
I major in Computer science in university in Korea.
This semester i got new task about TCP/IP. 
Our team should make a multi-chat program using open source on github. 
We founded your code at
<http://photo199.tistory.com/251>
and
<https://github.com/copcop/pineapple>.

Can we use this code the name of 'mumu chat' at our class? 
How about this code`s license. PLZ, note.

**Comment by doublemetal** [comment]
Ok. You can use my code as you like.
I appreciate your interest and hope to make a better program.

**Comment by ghost** [comment]
Thax, Kim. Always good luck to you!

2017-05-27 20:27 GMT+09:00 kim <notifications@github.com>:
